import { ConductorNumberAnalysisModel } from "../../../modules/numerology/models/conductor-number-analysis.model";

export function conductorNumberAnalysisDataInsert() {
  return ConductorNumberAnalysisModel.insertMany([
    {
      conductorNumber: 1,
      mainTitle: "Your Bhagyanka is 1",
      subTitle: "You have traits of a Sun/The King",
      language: "en",
      mainContent: [
        "You're smart, straightforward, funny, stubborn, hardworking, and honest. You have a competitive streak and can feel jealous in a competitive situation. Despite that, you have a kind heart, and you can get angry but are also friendly. You like being in authority and aspire to be famous. You always want to be regarded as first in people's eyes, preferring independence and avoiding being under others. Overall, you're self-confident.",
        "You're likely to experience love at a younger age, but you'll choose to get married when you mature. You may encounter challenges in relationships with those who hold opposite views.",
        "You're inclined to seek revenge against your enemies over the long term. While you tend to be a spender, your future holds promise for a successful and fulfilling profession.",
        "If you're a guy, you'll likely be very popular, attracting mental admiration and respect from everyone. Your positive attitude and talents in various areas make you stand out, allowing you to navigate seamlessly from local settings to the heart of the parliament. However, despite your smart behavior, there will always be some individuals working hard to bring you and your name down. This can be undercover, and your success may also attract some hatred from certain people.",
        "Your family life is fulfilling, with a wonderful partner and delightful children. You embody qualities of a pioneer-being independent and original in your approach to life.",
      ],
      subContent: [
        "You possess a strong character, akin to the sun, and it's often challenging for others to sway your opinions or change your mind.",
        "You demonstrate strong management and leadership skills, coupled with excellent motivational abilities. Your performance excels when entrusted with responsibilities and leadership positions.",
        "You are highly energetic and committed, completing tasks without leaving them unfinished. You prefer handling most of the work yourself, placing a strong belief in your abilities.",
        "Your mind remains steady, and it's challenging for others to sway your thoughts. You hold strong beliefs in your ideas and are not easily persuaded.",
        "You are creative and inventive, often generating ideas and solutions that think outside the box. Your originality is evident, and you tend not to copy others.",
        "You are highly optimistic, refusing to give up easily even in the face of challenging times or situations.",
        "At times, you may become overly ambitious.",
        "At times, you may tend to impose your ideas or decisions on others.",
        "You might find yourself frequently discussing your accomplishments and attempting to showcase your greatness.",
      ],
    },
    {
      conductorNumber: 1,
      mainTitle: "तुम्हारा भाग्यांक १ है",
      subTitle: "तुम्हारे पास सूरज/राजा के गुण हैं",
      language: "hi",
      mainContent: [
        "तुम चतुर, सीधे साधे, मजेदार, जिद्दी, मेहनती, और ईमानदार हो। तुम्हारी में दर्शक की भावना है, तुम प्रतियोगी स्थिति में ईर्ष्या महसूस कर सकते हो। फिर भी, तुम्हारे पास दयालु ह्रदय है, और तुम गुस्से में आ सकते हो, लेकिन मित्रवत स्वभाव भी है। तुम्हें अधिकार में रहना पसंद है और प्रसिद्ध होने का अभिलाषा है। तुम हमेशा लोगों की नज़रों में पहले होना चाहते हो, स्वतंत्रता पसंद करते हो और अन्यों के अधीन नहीं होना चाहते। समग्र रूप से, तुम स्व-विश्वासी हो।",
        "तुम्हें संभवतः युवा आयु में प्यार का अनुभव होगा, लेकिन जब तुम परिपक्व होंगे, तब तुम शादी करने का चयन करोगे। तुम्हें उन लोगों के साथ संबंधों में चुनौतियों का सामना करना पड़ सकता है जो विपरीत दृष्टिकोण रखते हैं।",
        "तुम्हें अपने दुश्मनों के प्रति प्रतिशोध लेने की प्रवृत्ति हो सकती है। हालांकि तुम खर्चे करने की प्रवृत्ति होते हो, लेकिन आपका भविष्य एक सफल और पूर्णजीवनी व्यवसाय के लिए वादा करता है।",
        "अगर तुम एक लड़का हो, तो तुम बहुत प्रसिद्ध हो सकते हो, सभी से मानसिक प्रशंसा और सम्मान प्राप्त करते हो। तुम्हारी सकारात्मक दृष्टिकोण और विभिन्न क्षेत्रों में अनुभव की तालिका में अद्वितीय गुण होने के कारण, तुम स्थानीय समारोहों से संसद के दिल तक सहजता से संचालित कर सकते हो। हालांकि, अपने चतुर व्यवहार के बावजूद, हमेशा कुछ व्यक्तियों का नाम और आपको नीचे लाने के लिए कठोर मेहनत करने वाले व्यक्तियों को हमेशा होता है। यह गुप्त रूप से हो सकता है, और आपकी सफलता भी कुछ लोगों से कुछ घृणा आकर्षित कर सकती है।",
        "तुम्हारा परिवारिक जीवन भरपूर है, एक अद्भुत संगी और दिलकश बच्चों के साथ। तुम जनक-स्वतंत्र और अनूठे होने के गुणों का प्रतिनिधित्व करते हो।",
      ],
      subContent: [
        "तुम्हारे पास एक मजबूत चरित्र है, सूर्य के समान, और दूसरों को अपने विचारों को बदलने या अपनी राय बदलने में अक्षम होता है।",
        "तुम प्रबंधन और नेतृत्व कौशल में मजबूत होते हो, साथ ही उत्तेजना देने की शानदार क्षमताओं के साथ। आपके प्रदर्शन में जब जिम्मेदारियों और नेतृत्व पदों को सौंपा जाता है, तो वह अत्यधिक होता है।",
        "तुम उच्च ऊर्जा और समर्पित होते हो, कार्यों को अधूरा नहीं छोड़ते। तुम अधिकांश काम को खुद ही संभालना पसंद करते हो, अपनी क्षमताओं में मजबूत विश्वास रखते हो।",
        "तुम्हारा मन स्थिर रहता है, और दूसरों को अपने विचारों को बदलने में कठिनाई होती है। तुम अपने विचारों में मजबूत विश्वास रखते हो और आसानी से प्रभावित नहीं होते।",
        "तुम रचनात्मक और आविष्कारशील होते हो, अक्सर विचार और समाधान उत्पन्न करते हो जो बाहर की सोच से होते हैं। तुम्हारी मूलभूतता प्रकट होती है, और तुम अक्सर दूसरों की नकल नहीं करते।",
        "तुम अत्यधिक आशावादी हो, मुश्किल समय या स्थितियों के सामने भी आसानी से हार नहीं मानते।",
        "कभी-कभी, तुम अत्यधिक महत्वाकांक्षी हो सकते हो।",
        "कभी-कभी, तुम अपने विचारों या निर्णयों को दूसरों पर थोपने की प्रवृत्ति रख सकते हो।",
        "तुम्हें संभवतः अपनी उपलब्धियों पर बार-बार चर्चा करने और अपनी महानता का प्रदर्शन करने की प्रवृत्ति हो सकती है।",
      ],
    },
    {
      conductorNumber: 1,
      mainTitle: "તમારો ભાગ્યાંક ૧ છે",
      subTitle: "તમારા પાસે સૂરજ/રાજાના ગુણ છે",
      language: "gu",
      mainContent: [
        "તમે ચતુર, સીધા, હાસ્યાંત, અડકવાળ, મહેનતી અને ઈમાનદાર છો. તમારી પાસે પ્રતિયોગિતાત્મક રીતે જેમ ઈર્ષ્યા અનુભવવાનું ભાવ રહે છે તે તમારી મિત્રતાનો હૃદય છે, અને તમે ગુસ્સે મુકી શકો છો, પરંતુ તમારી મિત્રતાયુક્ત પણ છે. તમને સર્વોચ્ચતામાં રહેવાનો ઇચ્છું છું અને નામાં પ્રથમની દૃષ્ટિમાં હંમેશા પ્રથમ જ રહેવું ઇચ્છો છો, સ્વતંત્રતાનો પ્રેરણા લેવું પસંદ કરો છો અને અન્યો અધીન નહીં રહી પસંદ કરો છો. સમગ્ર રીતે, તમે આત્મવિશ્વાસી છો.",
        "તમને યુવા ઉંમરમાં પ્રેમનો અનુભવ થઈ શકે છે, પરંતુ તમે પરિપક્વ થયા પછી લગ્ન કરવો પસંદ કરો છો. તમારી સાથે તે લોકો સાથે સંબંધોમાં ચુંટણીઓ અનુભવવા શકે છે જે વિરુદ્ધ વિચારો ધરાવે છે.",
        "તમે લાંબા અવધિ સુધી તમારા શત્રુઓ પર પ્રતિશોધ લેવાનું અનુભવો શકો છો. હાલમાં તમે ખર્ચવું પસંદ કરો છો, પરંતુ તમારું ભવિષ્ય એક યશસ્વી અને પૂર્ણજીવની વ્યવસાય માટે પ્રમાણપત્ર ધરાવે છે.",
        "જો તમે એક છો, તો તમને ખૂબ પ્રખ્યાત કરવાની પ્રવૃત્તિ છે, પ્રત્યેકોના માનસિક પ્રશંસા અને માનમાન મેળવતો છે. તમારું સકારાત્મક વર્તન અને વિવિધ વિચારાઓમાં તમારું મહત્વ ઉભે છે, જેથી તમે સ્થાનિક સેટિંગ્સથી સંસદના હૃદય સુધી સુસ્તિને સમજવા માટે આરામથી વહેંચી શકો છો. પરંતુ, તમારી ચતુર વર્તની સાથે પણ હંમેશા કેટલાય વ્યક્તિઓ તમારું નામ અને તમારા નામનું નામ લાવવા માટે મેહનત કરવા માટે મજબૂત છે. આ ગુપ્ત રીતે હોઈ શકે છે, અને તમારી સફળતા પણ કેટલાય લોકોની થોડી ઘૃણા આકર્ષિત કરી શકે છે.",
        "તમારી કુટુંબ જીવન પૂર્ણ છે, એક સમર્થ જીવન સાથે એક આદર્શ સાથી અને આનંદમય બાળકો સાથે. તમે જનકનો લેખો બીજા લોકો અને આપનું નામ નીચે લાવવા માટે સ્વતંત્રતાને પ્રતિષ્ઠા કરવાની ગુણવત્તા ધરાવવા માટે સ્વતંત્રતાનો પ્રતિષ્ઠા ધરાવવા માટે પછી એમનો ગર્વ છો.",
      ],
      subContent: [
        "તમારે સૂર્ય સમાન મજબૂત ચરિત્ર છે, અને દૂસરને તમારી રાય ફેરવવામાં અથવા તમારી મને બદલવામાં કઠીનતા અનુભવવામાં અક્ષમ હોવાનો જોખમ રહે છે.",
        "તમારી પ્રવર્તનશીલતા અને સારવાર કરવાની સ્વાસ્થ્ય પ્રવૃત્તિઓ અને સરસ પ્રેરણાશીલતાઓનો સંયુક્ત અતિ છે। તમારી પ્રદર્શન ઉત્કૃષ્ટ હોય છે કે ક્ષમતિઓ અને નેતૃત્વ જવાબદારીઓ અને નેતૃત્વ પદો પર નિર્માણ કરે છે.",
        "તમે ઘણી ઊર્જાશીલ અને પ્રતિબદ્ધ હોવા પસંદ કરો છો, કામોને અપૂર્ણ છોડવાનું નહીં. તમે અધિકાંશ કામોને ખુદે સંભાળવા પસંદ કરો છો, તમારી યોગ્યતાઓમાં અદ્યતન બધુ રહે છે.",
        "તમારું મન સ્થિર રહે છે, અને દૂસરોને તમારા વિચારો બદલવા માટે કઠિનીઓ હોય છે. તમે તમારા વિચારોમાં મજબૂત વિશ્વાસ ધરાવતા હો અને આસાનીથી પ્રભાવિત નહીં થાય છો.",
        "તમે રચનાત્મક અને આવિષ્કરશીલ હોવા પસંદ કરો છો, અક્સર વિચારો અને સમાધાનો ઉત્પન્ન કરવાની યોજના બાહ્ય થી હોય છે. તમારી મૌળિકતા પ્રગટ છે, અને તમે અન્યોની નકલ ન કરો છો.",
        "તમે અત્યધિક આશાવાદી હો શકે છો, મુશ્કિલ સમય અથવા સ્થિતિઓની સામે સુલભતા સ્થિતિઓ અને સમયમાં પણ આસાનીથી હાર ન માનવા પસંદ કરો છો.",
        "ક્યારેક ક્યારેક, તમે અત્યધિક મહત્વાકાંક્ષી હો શકે છો.",
        "ક્યારેક ક્યારેક, તમે દૂસરોને તમારા વિચારો અને નિર્ણયો થોપવાની પ્રવૃત્તિ ધરાવી શકો છો.",
        "તમે સંભવતઃ તમારી ઉપલબ્ધિઓ પર બારબાદી કરતા ક્યારેક વાર ચર્ચા કરવા અને તમારી મહાનતાને પ્રદર્શન કરવાની પ્રવૃત્તિ હો શકે છે.",
      ],
    },
    {
      conductorNumber: 2,
      mainTitle: "Your Bhagyanka is 2",
      subTitle: "You have traits of a Moon/The Queen",
      language: "en",
      mainContent: [
        "Regardless of everything, you'll be loved by everyone because your ruler is the moon, and everyone loves the moon. However, you tend to daydream a lot, have low self-confidence, and seek backup for every move in your life. You are quite unpredictable, displaying both selfish and selfless tendencies. Your strong sense of musical and artistic talent, along with verbal communication skills, is prominent.",
        "Your attitudes are like the moon—coming to gloom and fading away, so people can expect changes in you. You have the potential to be a force for peace and love, akin to Mahatma Gandhi, or harbor destructive tendencies like Hitler, depending on circumstances.",
        "If you deeply contemplate your beliefs in God, you'll find strength. Often, your words carry a sense of premonition, making you adept at predicting situations. You are likely to excel as poets, writers, or artistic businesspeople.",
        "In matters of love, you may not be strong, and you might experience shifts until marriage. If you're a woman, you'll be a responsible figure in the family. If you're a man, you may engage in fights and arguments within the family or vice versa, indicating a willingness to sacrifice for your family's well-being. You possess qualities of being gentle, intuitive, with a broad vision—a power behind the scenes",
      ],

      subContent: [
        "You are very romantic and sensitive, easily bothered by small things.",
        "You are creative and imaginative, excelling in art-related fields.",
        "You are normally gentle and peace-loving but can become moody.",
        "You are highly emotional, with a tendency to cry over small issues.",
        "You have highly intuitive brains, always thinking and working.",
        "You are a good speaker.",
        "You may experience mood swings and lack of self-confidence.",
        "Sometimes, you may feel depression.",
        "You are indecisive, often changing your decisions.",
        "Indecisiveness is a common trait among you. You often make decisions that may not be the best choices, and even after committing, you tend to reconsider and change your decisions multiple times.",
        "Some times you become impatient also.",
      ],
    },
    {
      conductorNumber: 2,
      mainTitle: "आपकी भाग्यांक २ है",
      subTitle: "आपके पास चंद्र/रानी के गुण हैं",
      language: "hi",
      mainContent: [
        "सब कुछ के बावजूद, आपको सभी पसंद करेंगे क्योंकि आपका शासक चंद्रमा है, और हर कोई चंद्रमा को पसंद करता है। हालांकि, आप बहुत सोच में पड़ने की प्रवृत्ति रखते हैं, कम आत्मविश्वास है, और अपने जीवन के प्रत्येक कदम के लिए सहारा चाहते हैं। आप बहुत अप्रत्याशित होते हैं, और स्वार्थी और बड़माशी के दोनों पक्षों का प्रदर्शन करते हैं। आपकी मजबूत संगीत और कलात्मक प्रतिभा, साथ ही वाचिक संचार कौशल, प्रमुख हैं।",
        "आपके नैतिकताएं चंद्रमा की तरह हैं - उदासी और अंधकार में आने के बाद, ताकि लोग आपमें बदलाव की उम्मीद कर सकें। आप शांति और प्रेम के लिए एक शक्ति के रूप में हो सकते हैं, महात्मा गांधी के समान, या परिस्थितियों के आधार पर हिटलर की तरह हानिकारक प्रवृत्तियों को गोद लेने के लिए।",
        "यदि आप ईश्वर में अपने विश्वासों पर गहराई से विचार करें, तो आपको ताकत मिलेगी। अक्सर, आपके शब्दों में पूर्वानुमान की भावना होती है, जिससे आप स्थितियों को पूर्वानुमानित करने में माहिर होते हैं। आप कवियों, लेखकों, या कलात्मक व्यवसायियों के रूप में उत्कृष्ट हो सकते हैं।",
        "प्रेम के मामलों में, आप मजबूत नहीं हो सकते, और आप लग्न तक स्थिति में परिवर्तन का अनुभव कर सकते हैं। अगर आप महिला हैं, तो आप परिवार में एक जिम्मेदार आकार हो सकते हैं। अगर आप पुरुष हैं, तो आप परिवार में लड़ाइयों और वाद-विवादों में शामिल हो सकते हैं, या उल्टे फिरते, अपने परिवार के भलाई के लिए बलिदान के लिए तैयार हो सकते हैं। आप मीठापन, प्रतिबद्धता, और व्यापक दृष्टिकोन की गुणवत्ता रखते हैं - साथ ही, एक छवि के पीछे की शक्ति",
      ],
      subContent: [
        "आप बहुत रोमांटिक और संवेदनशील हैं, छोटी बातों पर परेशान हो सकते हैं।",
        "आप रचनात्मक और कल्पनाशील हैं, कला संबंधी क्षेत्रों में उत्कृष्टता प्राप्त कर सकते हैं।",
        "आप सामान्यत: नम्र और शांति प्रिय हैं, लेकिन आप चंचल हो सकते हैं।",
        "आप बहुत ही भावनात्मक हैं, छोटी समस्याओं पर रोने की प्रवृत्ति है।",
        "आपके बहुत ही आंतरिक बुद्धि है, हमेशा सोच और काम कर रहे हैं।",
        "आप एक अच्छे वक्ता हैं।",
        "कभी-कभी, आप अवसाद महसूस कर सकते हैं।",
        "कभी-कभी, आप निर्णय लेने में असमर्थ हो सकते हैं।",
        "आपके निर्णयों में परिवर्तन की प्रवृत्ति हो सकती है।",
        "कभी-कभी आप अधीर हो सकते हैं।",
      ],
    },
    {
      conductorNumber: 2,
      mainTitle: "તમારો ભાગ્યાંક ૨ છે",
      subTitle: "તમારા પાસે ચંદ્ર/રાણીના ગુણ છે",
      language: "gu",
      mainContent: [
        "આશરે બધું, તમને દરેક પસંદ કરશે કારણકે તમારો શાસક ચંદ્ર છે અને દરેક ચંદ્રને પ્રેમ છે. પરંતુ, તમે ઘણી વિચારણા કરવાની પ્રવૃત્તિ ધરાવો છો, જેનાથી તમારો આત્મવિશ્વાસ ઓછો થાય છે, અને તમારી જીવનની દરેક હરકત માટે બેકઅપ માંગો છો. તમે ખૂબ અપ્રત્યક્ષ હોવાની પ્રવૃત્તિ ધરાવો છો, જે સ્વાર્થી અને આત્માર્પણ લાંબા છે. તમારી સંગીત અને કલાત્મક ક્ષમતાનો મજબૂત અને વાર્તાલાપી દક્ષતા, તેમજ ભાષણ ક્ષમતા, પ્રમુખ છે.",
        "તમારી રાજનીતિને ચંદ્ર જેવી પ્રવૃત્તિઓ છે - વિસ્મય માં આવ્યું અને સડકવ્યું, તો લોકો તમાં ફેરફાર કરવાની આશા કરી શકે છે. તમારી શાંતિ અને પ્રેમ માટે તાકાતની શક્તિ હોઈ શકે છે, જેમાં મહાત્મા ગાંધી સમાન, અથવા હિટલર જેવા વાતાવરણ પર ધ્યાન આપી શકે છે.",
        "જો તમે દેવની વિશ્વાસો પર ગંભીરભાવનાથી ચિંતન કરો, તો તમે શક્તિ મળે છે. અક્સર, તમારા શબ્દોમાં આગામીની સુચનાઓ હોઈ શકે છે, જેથી તમે સ્થિતિઓને ભવિષ્યવાણી કરવા માટે માહિર બની શકો છો. તમે કવિઓ, લેખકો, અથવા કલાત્મક વ્યવસાયી તરીકે ઉત્કૃષ્ટ હોઈ શકો છો.",
        "પ્રેમની વિશેષ વાતચીતની બાબતમાં, તમે મજબૂત ન હોવાનું અને તમે લગ્ન સુધી વળતરમાં પરિવર્તનો અનુભવ કરી શકો છો. જો તમે મહિલા હો, તો તમે પરિવારમાં એક જવાબદાર આકાર ધરાવી શકો છો. જો તમે પુરુષ હો, તો તમે પરિવાર માં લડાઇ અને વિવાદમાં લગેશો અને પરિવર્તનમાં રજીનું અને પરિવર્તનમાં અનુભવવામાં આભ્યાસી અંગીકારી અનુભવ કરી શકો છો. તમારી અદાકારતા, અંતઃપ્રેરણાદાયી અને પાંખો પછી અંદર શક્તિશાલી અંગીકરણ સાથે જાહેર છે.",
      ],
      subContent: [
        "તમે ખૂબ રોમાંચક અને સંવેદનશીલ છો, છોટા બાબતો પર આસાની થાય છો.",
        "તમે રચનાત્મક અને કલ્પનાશીલ છો, કલાની સંબંધિત ફીલ્ડમાં પ્રાવીણ્ય છે.",
        "તમે સામાન્યતઃ નમ્ર અને શાંતિપ્રિય છો, પરંતુ ક્રિયાત્મક થવા શકે છે.",
        "તમે ઘણી ભાવનાત્મક હોઈ શકો છો, લઘુ મુદ્દાઓ પર રોંધવાની પ્રવૃત્તિ છે.",
        "તમારી ઘણી અંતઃપ્રેરણાદાયી મનશ્શાસ્ત્રી છે, હંમેશા વિચારો અને કામ કરે છે.",
        "તમે સારું ભાષક છો.",
        "તમે મૂડ સ્વિંગ્સ અને આત્મવિશ્વાસ ની અભાવમાં અનુભવ કરી શકો છો.",
        "ક્યારેક ક્યારેક, તમે અવસાદ અનુભવ કરી શકો છો.",
        "તમે નિર્ણય લેવામાં અસમર્થ હોઈ શકો છો, તમારી નિર્ણયો પર સદાય ફેરફાર કરવાની પ્રવૃત્તિ છે.",
        "અસન્તોષ એ તમારી સામાન્ય ગુણવત્તા હોઈ શકે છે. ક્યારેક ક્યારેક, તમે ધીમું બની જશો.",
        "ક્યારેક ક્યારેક, તમે અધીર બની જશો.",
      ],
    },
    {
      conductorNumber: 3,
      mainTitle: "Your Bhagyanka is 3",
      subTitle: "You have traits of a Jupiter/The Counsellor",
      language: "en",
      mainContent: [
        "You are characterized as a person with a hard-hearted and often selfish demeanor. Despite experiencing numerous family problems in the early stages of your life, you endure through everything with a strong will and a happy facade. Your determination and assertiveness help you consistently achieve your desires. From the outset, your life has been centered around hard work and the pursuit of accomplishments.",
        "Dealing with you is not easy, as you are a tough competitor, but if someone's attitude impresses you, a lasting friendship is likely. While you may face worries and problems, they are expected to be temporary, and you will be blessed with brilliant children. Money holds a significant place in your life, driving you to strive for financial success. If you are a man, your lifetime is marked by generosity and kindness toward your family and friends. As a woman, you possess good character, cultural values, and a hardworking attitude.",
        "You are a freedom lover, creative, and ambition-focused, bringing beauty, hope, and joy to the world.",
      ],
      subContent: [
        "You are confident about your abilities and often take a leadership role, showcasing outstanding management qualities.",
        "Honesty is a key trait, and you navigate smartly while maintaining integrity. Your intelligence plays a significant role in your rise in life.",
        "Diplomacy is one of your strengths; you tend to say yes to everything but ultimately prioritize what brings you pleasure. You can control your temper and avoid unnecessary arguments.",
        "Early in your career, you may face struggles that contribute to your growth and ultimate success.",
        "Discipline is a notable characteristic, and you adhere to rules, solving problems with intelligence and without breaking laws.",
        "Positive energy and confidence are prevalent in your personality, and you never lose hope.",
        "You work in a planned manner and strive for task completion once initiated. Helping others is a common inclination for you.",
        "Ambition drives you to pursue various avenues for earning money.",
        "At times, you may experience moments of sadness.",
        "Occasionally, you become overly optimistic.",
        "Restlessness may be felt at certain points in your life.",
      ],
    },
    {
      conductorNumber: 3,
      mainTitle: "आपका भाग्यांक ३ है",
      subTitle: "आपमें बृहस्पति/परामर्शदाता के गुण हैं",
      language: "hi",
      mainContent: [
        "आपकी पहचान कठोर दिल वाले और अक्सर स्वार्थी आचरण वाले व्यक्ति के रूप में की जाती है। अपने जीवन के शुरुआती दौर में कई पारिवारिक समस्याओं का सामना करने के बावजूद, आप दृढ़ इच्छाशक्ति और प्रसन्न चेहरे के साथ हर चीज का सामना करते हैं। आपका दृढ़ संकल्प और दृढ़ता आपको लगातार मदद करती है अपनी इच्छाओं को प्राप्त करें। शुरू से ही, आपका जीवन कड़ी मेहनत और उपलब्धियों की खोज पर केंद्रित रहा है।",
        "आपसे निपटना आसान नहीं है, क्योंकि आप एक कठिन प्रतिस्पर्धी हैं, लेकिन अगर किसी का रवैया आपको प्रभावित करता है, तो एक स्थायी दोस्ती की संभावना है। हालांकि आपको चिंताओं और समस्याओं का सामना करना पड़ सकता है, लेकिन वे अस्थायी होने की उम्मीद है, और आप प्रतिभाशाली होंगे बच्चे। पैसा आपके जीवन में एक महत्वपूर्ण स्थान रखता है, जो आपको वित्तीय सफलता के लिए प्रयास करने के लिए प्रेरित करता है। यदि आप एक पुरुष हैं, तो आपका जीवनकाल आपके परिवार और दोस्तों के प्रति उदारता और दयालुता से चिह्नित है। एक महिला के रूप में, आपके पास अच्छे चरित्र और सांस्कृतिक मूल्य हैं , और एक मेहनती रवैया।",
        "आप एक स्वतंत्रता प्रेमी, रचनात्मक और महत्वाकांक्षा-केंद्रित हैं, जो दुनिया में सुंदरता, आशा और खुशी लाते हैं।",
      ],
      subContent: [
        "आप अपनी क्षमताओं के बारे में आश्वस्त हैं और उत्कृष्ट प्रबंधन गुणों का प्रदर्शन करते हुए अक्सर नेतृत्व की भूमिका निभाते हैं।",
        "ईमानदारी एक प्रमुख गुण है, और आप ईमानदारी बनाए रखते हुए चतुराई से आगे बढ़ते हैं। आपकी बुद्धिमत्ता जीवन में आपके उत्थान में महत्वपूर्ण भूमिका निभाती है।",
        "कूटनीति आपकी शक्तियों में से एक है; आप हर बात के लिए हाँ कहते हैं लेकिन अंततः उस चीज़ को प्राथमिकता देते हैं जो आपको खुशी देती है। आप अपने गुस्से पर नियंत्रण रख सकते हैं और अनावश्यक तर्क-वितर्क से बच सकते हैं।",
        "अपने करियर की शुरुआत में, आपको संघर्षों का सामना करना पड़ सकता है जो आपके विकास और अंतिम सफलता में योगदान देता है।",
        "अनुशासन एक उल्लेखनीय विशेषता है, और आप नियमों का पालन करते हैं, समस्याओं को बुद्धिमत्ता से और कानून तोड़े बिना सुलझाते हैं।",
        "आपके व्यक्तित्व में सकारात्मक ऊर्जा और आत्मविश्वास व्याप्त है, और आप कभी उम्मीद नहीं खोते।",
        "आप योजनाबद्ध तरीके से काम करते हैं और एक बार काम शुरू करने के बाद उसे पूरा करने का प्रयास करते हैं। दूसरों की मदद करना आपके लिए एक सामान्य प्रवृत्ति है।",
        "महत्वाकांक्षा आपको पैसे कमाने के लिए विभिन्न रास्ते अपनाने के लिए प्रेरित करती है।",
        "कभी-कभी, आपको दुःख के क्षणों का अनुभव हो सकता है।",
        "कभी-कभी, आप अत्यधिक आशावादी हो जाते हैं।",
        "आपके जीवन में कुछ बिंदुओं पर बेचैनी महसूस हो सकती है।",
      ],
    },
    {
      conductorNumber: 3,
      mainTitle: "તમારી ભાગ્યાંક ૩ છે",
      subTitle: "તમારામાં ગુરુ/કાઉન્સેલરના લક્ષણો છે",
      language: "gu",
      mainContent: [
        "તમે કઠણ હૃદયવાળા અને ઘણીવાર સ્વાર્થી વર્તન ધરાવતા વ્યક્તિ તરીકે દર્શાવવામાં આવ્યા છો. તમારા જીવનના પ્રારંભિક તબક્કામાં અસંખ્ય પારિવારિક સમસ્યાઓનો અનુભવ કરવા છતાં, તમે મજબૂત ઇચ્છા અને ખુશ રવેશ સાથે દરેક બાબતમાં સહન કરો છો. તમારો નિશ્ચય અને અડગતા તમને સતત મદદ કરે છે. તમારી ઇચ્છાઓને પ્રાપ્ત કરો, શરૂઆતથી જ તમારું જીવન સખત મહેનત અને સિદ્ધિઓની શોધ પર કેન્દ્રિત છે.",
        "તમારી સાથે વ્યવહાર કરવો સહેલું નથી, કારણ કે તમે સખત હરીફ છો, પરંતુ જો કોઈનું વલણ તમને પ્રભાવિત કરે છે, તો કાયમી મિત્રતાની સંભાવના છે. જ્યારે તમે ચિંતાઓ અને સમસ્યાઓનો સામનો કરી શકો છો, તે કામચલાઉ હોવાની અપેક્ષા છે, અને તમને તેજસ્વી સાથે આશીર્વાદ મળશે. બાળકો તમારા જીવનમાં એક મહત્વપૂર્ણ સ્થાન ધરાવે છે, જો તમે એક પુરુષ છો, તો તમારું જીવન તમારા કુટુંબ અને મિત્રો પ્રત્યે ઉદારતા, સાંસ્કૃતિક મૂલ્યો ધરાવે છે , અને મહેનતુ વલણ.",
        "તમે સ્વતંત્રતા પ્રેમી, સર્જનાત્મક અને મહત્વાકાંક્ષા-કેન્દ્રિત છો, જે વિશ્વમાં સૌંદર્ય, આશા અને આનંદ લાવે છે.",
      ],
      subContent: [
        "તમે તમારી ક્ષમતાઓ વિશે વિશ્વાસ ધરાવો છો અને ઘણી વખત નેતૃત્વની ભૂમિકા નિભાવો છો, ઉત્કૃષ્ટ મેનેજમેન્ટ ગુણોનું પ્રદર્શન કરો.",
        "પ્રમાણિકતા એ મુખ્ય લક્ષણ છે, અને તમે પ્રામાણિકતા જાળવીને સ્માર્ટ રીતે નેવિગેટ કરો છો. તમારી બુદ્ધિ તમારા જીવનમાં તમારા ઉદયમાં મહત્વપૂર્ણ ભૂમિકા ભજવે છે.",
        "મુત્સદ્દીગીરી એ તમારી શક્તિઓમાંની એક છે; તમે દરેક વસ્તુ માટે હા કહેવાનું વલણ રાખો છો પરંતુ આખરે તમને જે આનંદ આપે છે તેને પ્રાથમિકતા આપો છો. તમે તમારા ગુસ્સાને નિયંત્રિત કરી શકો છો અને બિનજરૂરી દલીલો ટાળી શકો છો.",
        "તમારી કારકિર્દીની શરૂઆતમાં, તમે સંઘર્ષનો સામનો કરી શકો છો જે તમારી વૃદ્ધિ અને અંતિમ સફળતામાં ફાળો આપે છે.",
        "શિસ્ત એ એક નોંધપાત્ર લાક્ષણિકતા છે, અને તમે નિયમોનું પાલન કરો છો, બુદ્ધિથી અને કાયદા તોડ્યા વિના સમસ્યાઓ હલ કરો છો.",
        "તમારા વ્યક્તિત્વમાં હકારાત્મક ઉર્જા અને આત્મવિશ્વાસ પ્રવર્તે છે, અને તમે ક્યારેય આશા ગુમાવતા નથી.",
        "તમે આયોજિત રીતે કામ કરો છો અને એકવાર શરૂ કર્યા પછી કાર્ય પૂર્ણ કરવા માટે પ્રયત્ન કરો છો. અન્યને મદદ કરવી એ તમારા માટે સામાન્ય ઝોક છે.",
        "મહત્વાકાંક્ષા તમને પૈસા કમાવવા માટે વિવિધ માર્ગો શોધવા માટે પ્રેરિત કરે છે.",
        "ક્યારેક, તમે ઉદાસી ની ક્ષણો અનુભવી શકો છો.",
        "ક્યારેક, તમે વધુ પડતા આશાવાદી બનો છો.",
        "તમારા જીવનના અમુક તબક્કે બેચેની અનુભવાઈ શકે છે.",
      ],
    },
    {
      conductorNumber: 4,
      mainTitle: "Your Bhagyanka is 4",
      subTitle: "You have traits of a Rahu/The Daredevil",
      language: "en",
      mainContent: [
        "You possess a stubborn nature and work diligently, yet you face challenges in crucial aspects of life. Despite your cool and helpful demeanor, your strong-worded expressions may push people away, especially if you're a man. You have a keen understanding of others and their problems. If you're a girl, you excel in studies and the arts. As a guy, you may indulge in a fun-filled life with friends and girls, but be cautious, as you might find yourself empty-handed due to the demands on your time and money.",
        "Your goodwill is evident in your constant support for family and friends, making you little gems, especially the girls. Love often finds you at a younger age, but disappointments, such as unemployment or ordinary jobs despite having a degree, may persist. Nevertheless, you excel in caring for your family. Be vigilant against those who might take advantage of your kind heart, including relatives.",
        "Your characteristics include being radical, patient, persistent, a bit old-fashioned, and living with a foundation of order",
        "If you were born on the 4th, 13th, 22nd, or 31st day of any month as a Psychic Number 4 person:",
      ],
      subContent: [
        "You are highly dedicated to your work, with abundant energy to work late hours, showcasing a hardworking nature.",
        "Your communication skills are proficient.",
        "Patience is a strong suit for you.",
        "You approach problems pragmatically and generously.",
        "While you don't trust easily, once trust is established, you become a reliable friend who stands by others in need.",
        "Life often presents sudden changes and ups and downs for you.",
        "Success requires persistent effort, and even if achieved easily, sustaining it proves challenging.",
        "Doubtfulness and difficulty in trusting others may arise.",
        "Relationship problems may surface, requiring careful consideration before marriage.",
        "Your temperament can be sweet and gentle or moody.",
        "There is a tendency to spend money lavishly.",
        "You may rebel against following rules.",
        "You may feel misunderstood and lonely, but you possess high intelligence and intellectual abilities.",
      ],
    },
    {
      conductorNumber: 4,
      mainTitle: "आपका भाग्यांक ४ है",
      subTitle: "आपमें राहु/साहसी के लक्षण हैं",
      language: "hi",
      mainContent: [
        "आप जिद्दी स्वभाव के हैं और लगन से काम करते हैं, फिर भी आपको जीवन के महत्वपूर्ण पहलुओं में चुनौतियों का सामना करना पड़ता है। आपके शांत और मददगार व्यवहार के बावजूद, आपके मजबूत शब्दों वाले भाव लोगों को दूर धकेल सकते हैं, खासकर यदि आप एक पुरुष हैं। आपके पास गहरी समझ है दूसरों और उनकी समस्याओं के बारे में। यदि आप एक लड़की हैं, तो आप पढ़ाई और कला में उत्कृष्ट हैं, एक लड़के के रूप में, आप दोस्तों और लड़कियों के साथ मौज-मस्ती भरी जिंदगी जी सकते हैं, लेकिन सावधान रहें, क्योंकि आप खुद को खाली महसूस कर सकते हैं। आपके समय और धन की माँग के कारण सौंपा गया।",
        "आपकी सद्भावना परिवार और दोस्तों के लिए आपके निरंतर समर्थन में स्पष्ट है, जो आपको छोटे रत्न बनाती है, खासकर लड़कियों को। प्यार अक्सर आपको कम उम्र में मिल जाता है, लेकिन डिग्री होने के बावजूद बेरोजगारी या साधारण नौकरी जैसी निराशाएं बनी रह सकती हैं। फिर भी , आप अपने परिवार की देखभाल करने में उत्कृष्ट हैं। उन लोगों से सतर्क रहें जो आपके दयालु हृदय का फायदा उठा सकते हैं, जिनमें रिश्तेदार भी शामिल हैं।",
        "आपकी विशेषताओं में कट्टरपंथी, धैर्यवान, लगातार बने रहना, थोड़ा पुराने जमाने का होना और व्यवस्था की नींव के साथ रहना शामिल है",
        "यदि आपका जन्म किसी भी महीने की 4, 13, 22 या 31 तारीख को मानसिक अंक 4 वाले व्यक्ति के रूप में हुआ है:",
      ],
      subContent: [
        "आप अपने काम के प्रति अत्यधिक समर्पित हैं, आपके पास देर तक काम करने के लिए प्रचुर ऊर्जा है, जो एक मेहनती स्वभाव का प्रदर्शन करता है।",
        "आपका संचार कौशल कुशल है।",
        "धैर्य आपके लिए एक मजबूत सूट है।",
        "आप समस्याओं को व्यावहारिक और उदारतापूर्वक देखते हैं।",
        "हालाँकि आप आसानी से भरोसा नहीं करते हैं, एक बार भरोसा स्थापित हो जाने पर, आप एक विश्वसनीय मित्र बन जाते हैं जो जरूरतमंदों के साथ खड़ा होता है।",
        "जिंदगी अक्सर आपके लिए अचानक बदलाव और उतार-चढ़ाव लेकर आती है।",
        "सफलता के लिए निरंतर प्रयास की आवश्यकता होती है, और यदि यह आसानी से प्राप्त भी हो जाए, तो भी इसे बनाए रखना चुनौतीपूर्ण साबित होता है।",
        "संदेह और दूसरों पर भरोसा करने में कठिनाई उत्पन्न हो सकती है।",
        "रिश्ते में समस्याएँ सामने आ सकती हैं, जिस पर शादी से पहले सावधानीपूर्वक विचार करने की आवश्यकता है।",
        "आपका स्वभाव मधुर और सौम्य या मूडी हो सकता है।",
        "पैसे को खुले दिल से खर्च करने की प्रवृत्ति होती है।",
        "आप निम्नलिखित नियमों के विरुद्ध विद्रोह कर सकते हैं।",
        "आपको गलत समझा जा सकता है और आप अकेलापन महसूस कर सकते हैं, लेकिन आपके पास उच्च बुद्धि और बौद्धिक क्षमताएं हैं।",
      ],
    },
    {
      conductorNumber: 4,
      mainTitle: "તમારી ભાગ્યાંક ૪ છે",
      subTitle: "તમારી પાસે રાહુ/ધ ડેરડેવિલના લક્ષણો છે",
      language: "gu",
      mainContent: [
        "તમે હઠીલા સ્વભાવ ધરાવો છો અને ખંતપૂર્વક કામ કરો છો, તેમ છતાં તમે જીવનના નિર્ણાયક પાસાઓમાં પડકારોનો સામનો કરો છો. તમારા ઠંડા અને મદદરૂપ વર્તન હોવા છતાં, તમારા મજબૂત શબ્દોના અભિવ્યક્તિઓ લોકોને દૂર ધકેલશે, ખાસ કરીને જો તમે માણસ છો. તમારી પાસે ઊંડી સમજ છે. અન્ય અને તેમની સમસ્યાઓ જો તમે એક છોકરી છો, તો તમે એક વ્યક્તિ તરીકે, તમે મિત્રો અને છોકરીઓ સાથે આનંદથી ભરપૂર જીવન જીવી શકો છો, પરંતુ સાવચેત રહો, કારણ કે તમે તમારી જાતને ખાલી શોધી શકો છો. તમારા સમય અને પૈસાની માંગને કારણે સોંપવામાં આવી છે.",
        "તમારી સદ્ભાવના તમારા કુટુંબ અને મિત્રો માટેના સતત સમર્થનમાં સ્પષ્ટ થાય છે, જે તમને નાના રત્નો બનાવે છે, ખાસ કરીને છોકરીઓ. પ્રેમ ઘણીવાર તમને નાની ઉંમરે શોધે છે, પરંતુ ડિગ્રી હોવા છતાં બેરોજગારી અથવા સામાન્ય નોકરીઓ જેવી નિરાશાઓ ચાલુ રહી શકે છે. તેમ છતાં , તમે તમારા પરિવારની સંભાળ રાખવામાં ઉત્કૃષ્ટ બનો છો, જેઓ તમારા દયાળુ હૃદયનો લાભ લઈ શકે છે, સંબંધીઓ સહિત.",
        "તમારી લાક્ષણિકતાઓમાં કટ્ટરપંથી, દર્દી, નિરંતર, થોડા જૂના જમાનાનું અને વ્યવસ્થાના પાયા સાથે જીવવું શામેલ છે",
        "જો તમારો જન્મ કોઈપણ મહિનાના 4ઠ્ઠા, 13મી, 22મી અથવા 31મી તારીખે માનસિક નંબર 4 વ્યક્તિ તરીકે થયો હોય તો:",
      ],
      subContent: [
        "તમે તમારા કામ માટે ખૂબ જ સમર્પિત છો, મોડે સુધી કામ કરવા માટે વિપુલ ઊર્જા સાથે, મહેનતુ સ્વભાવનું પ્રદર્શન કરો.",
        "તમારી સંચાર કુશળતા નિપુણ છે.",
        "ધૈર્ય તમારા માટે એક મજબૂત પોશાક છે.",
        "તમે વ્યવહારિક અને ઉદારતાથી સમસ્યાઓનો સંપર્ક કરો છો.",
        "જ્યારે તમે સરળતાથી વિશ્વાસ કરતા નથી, એકવાર વિશ્વાસ સ્થાપિત થઈ જાય, પછી તમે એક વિશ્વાસપાત્ર મિત્ર બનશો જે અન્ય જરૂરિયાતમંદોની પડખે રહે છે.",
        "જીવન ઘણીવાર તમારા માટે અચાનક ફેરફારો અને ઉતાર-ચઢાવ રજૂ કરે છે.",
        "સફળતા માટે સતત પ્રયત્નોની જરૂર પડે છે, અને જો સરળતાથી પ્રાપ્ત થાય તો પણ તેને ટકાવી રાખવું પડકારરૂપ સાબિત થાય છે.",
        "સંદેહ અને અન્ય પર વિશ્વાસ કરવામાં મુશ્કેલી ઊભી થઈ શકે છે.",
        "સંબંધની સમસ્યાઓ સપાટી પર આવી શકે છે, લગ્ન પહેલાં સાવચેતીપૂર્વક વિચારણાની જરૂર છે.",
        "તમારો સ્વભાવ મીઠો અને નમ્ર અથવા મૂડી હોઈ શકે છે.",
        "પૈસાનો ઉમળકાભેર ખર્ચ કરવાની વૃત્તિ છે.",
        "તમે નીચેના નિયમો સામે બળવો કરી શકો છો.",
        "તમે ગેરસમજ અને એકલતા અનુભવી શકો છો, પરંતુ તમારી પાસે ઉચ્ચ બુદ્ધિ અને બૌદ્ધિક ક્ષમતાઓ છે.",
      ],
    },
    {
      conductorNumber: 5,
      mainTitle: "Your Bhagyanka is 5",
      subTitle: "You have traits of a Mercury/The Prince",
      language: "en",
      mainContent: [
        `You are highly popular within the community, effortlessly getting things done through conversations, even with enemies. Possessing a sharp business mind, you often live in the moment, acting on the impulse of "let's do this." Opening a business, getting involved in share dealings, or pursuing music can make you famous. With a great sense of humor, you are the go-to person for friends and family seeking help, even extending financial assistance.`,
        `While you may have multiple relationships, settling down makes you a bit selfish, with your significant other having considerable control over you. It's important to be cautious as you tend to maintain other relationships, even when married, due to your popularity.`,
        `Being the middle number, you easily get along with anyone, embracing change and freedom as an enthusiast and explorer with a charismatic presence.`,
        `If you were born on the 5th, 14th, or 23rd day of any month as a Psychic Number 5 person:`,
      ],
      subContent: [
        "You are intelligent and a fast thinker, quick to answer questions or provide solutions, though your minds can change frequently.",
        `Versatility is a strong suit, and you prefer variety over long-term plans, embracing change enthusiastically.`,
        `Creativity flows naturally, and you strive to generate unique ideas without copying others.`,
        `Strong communication skills are evident, allowing you to impress people effortlessly.`,
        `Jovial and lively by nature, you can quickly lighten up any environment.`,
        `Flexibility and adaptability make you easily approachable, but you may be less flexible in your own home, resisting changes to your arrangements.`,
        `A youthful and optimistic nature dominates, though occasional bouts of depression may occur.`,
        `Talking too much can be a tendency at times.`,
        `Ego-related issues may arise intermittently.`,
        `Moody periods can surface.`,
        `A love for traveling is a prominent characteristic.`,
        `Health-conscious with careful food selection and attention to physical appearance.`,
        `Intuition is a notable trait.`,
      ],
    },
    {
      conductorNumber: 5,
      mainTitle: "आपका भाग्यांक ५ है",
      subTitle: "आपमें बुध/राजकुमार के लक्षण हैं",
      language: "hi",
      mainContent: [
        `आप समुदाय के भीतर बेहद लोकप्रिय हैं, यहां तक कि दुश्मनों से भी बातचीत के जरिए आसानी से काम निपटा लेते हैं। एक तेज़ व्यावसायिक दिमाग रखने के कारण, आप अक्सर "चलो यह करते हैं" के आवेग पर कार्य करते हुए, उस क्षण में रहते हैं। कोई व्यवसाय खोलना, शेयर डीलिंग में शामिल होना या संगीत में रुचि लेना आपको प्रसिद्ध बना सकता है। हास्य की एक महान भावना के साथ, आप दोस्तों और परिवार के पास मदद मांगने वाले व्यक्ति हैं, यहां तक कि वित्तीय सहायता भी प्रदान करते हैं।`,
        "हालाँकि आपके कई रिश्ते हो सकते हैं, लेकिन एक साथ बसने से आप थोड़े स्वार्थी हो जाते हैं, जबकि आपके महत्वपूर्ण दूसरे का आप पर काफी नियंत्रण होता है। सतर्क रहना महत्वपूर्ण है क्योंकि आप अपनी लोकप्रियता के कारण, शादीशुदा होते हुए भी अन्य रिश्ते बनाए रखते हैं।",
        `मध्य अंक होने के कारण, आप आसानी से किसी के भी साथ घुलमिल जाते हैं, एक करिश्माई उपस्थिति के साथ एक उत्साही और खोजकर्ता के रूप में परिवर्तन और स्वतंत्रता को अपनाते हैं।`,
        `यदि आपका जन्म किसी भी महीने की 5, 14, या 23 तारीख को मानसिक अंक 5 वाले व्यक्ति के रूप में हुआ है:`,
      ],
      subContent: [
        `आप बुद्धिमान और तेज़ विचारक हैं, सवालों के तुरंत जवाब देते हैं या समाधान देते हैं, हालांकि आपका दिमाग बार-बार बदल सकता है।`,
        `बहुमुखी प्रतिभा एक मजबूत पक्ष है, और आप दीर्घकालिक योजनाओं के बजाय विविधता को प्राथमिकता देते हैं, परिवर्तन को उत्साहपूर्वक अपनाते हैं।`,
        `रचनात्मकता स्वाभाविक रूप से बहती है, और आप दूसरों की नकल किए बिना अद्वितीय विचार उत्पन्न करने का प्रयास करते हैं।`,
        `मजबूत संचार कौशल स्पष्ट है, जिससे आप लोगों को सहजता से प्रभावित कर सकते हैं।`,
        `स्वभाव से प्रसन्नचित्त और जीवंत, आप किसी भी वातावरण को तुरंत खुशनुमा बना सकते हैं।`,
        `लचीलापन और अनुकूलनशीलता आपको आसानी से पहुंचने योग्य बनाती है, लेकिन आप अपने घर में कम लचीले हो सकते हैं, और अपनी व्यवस्थाओं में बदलाव का विरोध कर सकते हैं।`,
        `एक युवा और आशावादी स्वभाव हावी है, हालांकि कभी-कभी अवसाद के दौरे भी पड़ सकते हैं।`,
        `कभी-कभी बहुत अधिक बातें करना एक प्रवृत्ति हो सकती है।`,
        `अहंकार से संबंधित मुद्दे रुक-रुक कर उठ सकते हैं।`,
        `मूडी पीरियड्स सामने आ सकते हैं।`,
        `यात्रा के प्रति प्रेम एक प्रमुख विशेषता है।`,
        `सावधानीपूर्वक भोजन चयन और शारीरिक बनावट पर ध्यान देने के साथ स्वास्थ्य के प्रति सचेत रहें।`,
        `अंतर्ज्ञान एक उल्लेखनीय गुण है।`,
      ],
    },
    {
      conductorNumber: 5,
      mainTitle: "તમારી ભાગ્યાંક ૫ છે",
      subTitle: "તમારી પાસે બુધ / રાજકુમારના લક્ષણો છે",
      language: "gu",
      mainContent: [
        `તમે સમુદાયમાં ખૂબ જ લોકપ્રિય છો, દુશ્મનો સાથે પણ વાતચીત દ્વારા સરળતાથી વસ્તુઓ કરી શકો છો. તીક્ષ્ણ વ્યવસાયિક મન ધરાવતા, તમે "ચાલો આ કરીએ." ધંધો ખોલવો, શેર ડીલિંગમાં સામેલ થવું અથવા સંગીતનો પીછો કરવો તમને પ્રખ્યાત બનાવી શકે છે. રમૂજની મહાન ભાવના સાથે, તમે મિત્રો અને કુટુંબીજનો માટે મદદ માગતા વ્યક્તિ છો, આર્થિક સહાય પણ લંબાવી શકો છો.`,
        `જ્યારે તમારી પાસે બહુવિધ સંબંધો હોઈ શકે છે, ત્યારે સ્થાયી થવાથી તમે થોડા સ્વાર્થી બની શકો છો, અને તમારા નોંધપાત્ર અન્ય તમારા પર નોંધપાત્ર નિયંત્રણ ધરાવે છે. સાવચેત રહેવું મહત્વપૂર્ણ છે કારણ કે તમે તમારી લોકપ્રિયતાને કારણે લગ્ન કર્યા પછી પણ અન્ય સંબંધો જાળવી રાખવાનું વલણ રાખો છો.`,
        `મધ્યમ નંબર હોવાને કારણે, તમે એક ઉત્સાહી અને પ્રભાવશાળી હાજરી સાથે સંશોધક તરીકે પરિવર્તન અને સ્વતંત્રતાને સ્વીકારીને સરળતાથી કોઈની પણ સાથે મળી શકશો.`,
        `જો તમારો જન્મ કોઈપણ મહિનાની 5મી, 14મી અથવા 23મી તારીખે માનસિક નંબર 5 વ્યક્તિ તરીકે થયો હોય તો:`,
      ],
      subContent: [
        "તમે બુદ્ધિશાળી અને ઝડપી વિચારક છો, પ્રશ્નોના જવાબ આપવામાં અથવા ઉકેલો આપવા માટે ઝડપી છો, જો કે તમારું મન વારંવાર બદલાઈ શકે છે.",
        `વર્સેટિલિટી એક મજબૂત પોશાક છે, અને તમે લાંબા ગાળાની યોજનાઓ કરતાં વિવિધતા પસંદ કરો છો, પરિવર્તનને ઉત્સાહપૂર્વક સ્વીકારો છો.`,
        `સર્જનાત્મકતા કુદરતી રીતે વહે છે, અને તમે અન્યની નકલ કર્યા વિના અનન્ય વિચારો પેદા કરવાનો પ્રયત્ન કરો છો.`,
        `મજબૂત સંચાર કૌશલ્ય સ્પષ્ટ છે, જેનાથી તમે લોકોને સહેલાઈથી પ્રભાવિત કરી શકો છો.`,
        `પ્રસન્નતાપૂર્ણ અને સ્વભાવે જીવંત, તમે કોઈપણ વાતાવરણને ઝડપથી હળવા કરી શકો છો.`,
        `લવચીકતા અને અનુકૂલનક્ષમતા તમને સહેલાઈથી પહોંચવા યોગ્ય બનાવે છે, પરંતુ તમે તમારા પોતાના ઘરમાં ઓછા લવચીક બની શકો છો, તમારી ગોઠવણમાં થતા ફેરફારોનો પ્રતિકાર કરી શકો છો.`,
        `યુવાન અને આશાવાદી સ્વભાવ પ્રભુત્વ ધરાવે છે, જોકે પ્રસંગોપાત ડિપ્રેશનનો સામનો કરવો પડી શકે છે.`,
        "ખૂબ વધુ બોલવું એ અમુક સમયે વલણ હોઈ શકે છે.",
        `અહંકાર સંબંધિત સમસ્યાઓ વચ્ચે-વચ્ચે ઊભી થઈ શકે છે.`,
        `મૂડી પીરિયડ્સ સપાટી પર આવી શકે છે.`,
        `પ્રવાસ માટેનો પ્રેમ એ એક આગવી લાક્ષણિકતા છે.`,
        "સાવધાનીપૂર્વક ખોરાકની પસંદગી અને શારીરિક દેખાવ પર ધ્યાન સાથે સ્વાસ્થ્ય પ્રત્યે સભાન.",
        "અંતર્જ્ઞાન એ એક નોંધપાત્ર લક્ષણ છે.",
      ],
    },
    {
      conductorNumber: 6,
      mainTitle: "Your Bhagyanka is 6",
      subTitle: "You have traits of a Venus",
      language: "en",
      mainContent: [
        `You are born to savor life, prioritizing enjoyment and caring less about others' opinions. Whether it's in education, work, or business management, you excel, displaying talent, kindness (to those you consider nice), and attractiveness to beautiful individuals. Luck seems to favor you in various aspects of life.`,
        `If you are a number six man, you might experience attention from many girls and engage in multiple relationships before settling down. If you are a girl, early marriage or engagement is common. Your concern for family and friends is evident.`,
        `Approaching the halfway mark, you may face physical and mental challenges. Generally, you foster inner-home happiness and possess qualities of compassion, comfort, fairness, domestic responsibility, and good judgment. Your caring nature has the power to contribute to a more loving world.`,
      ],
      subContent: [
        `Fortune smiles upon you, providing luxurious possessions like cars, houses, expensive mobiles, watches, and dresses. Regardless of age, you maintain a youthful outlook on life, seeking enjoyment.`,
        `A magnetic and attractive personality makes you well-known within your group or friend circle, attracting attention from the opposite sex.`,
        `Creativity is a strong suit, and you excel as an entertainer.`,
        `Responsibility is part of your nature, making you reliable and effective as a manager.`,
        `Consciousness of your physical appearance is apparent.`,
        `You avoid disturbed environments and arguments, yet can be a formidable opponent in a debate.`,
        `Romantic with expertise in the art of love, you may have many relationships.`,
        `Spending freely on luxury items or necessities is common.`,
        `Appreciation for beauty extends to various aspects of life.`,
        `Emotional depth is a characteristic, but you might get bored in love easily.`,
        `Innovative thinking and a preference for change are notable traits.`,
        `Periods of laziness and lack of energy may be experienced.`,
      ],
    },
    {
      conductorNumber: 6,
      mainTitle: "आपका भाग्यांक ६ है",
      subTitle: "आपमें शुक्र ग्रह के लक्षण हैं",
      language: "hi",
      mainContent: [
        `आपका जन्म जीवन का आनंद लेने, आनंद को प्राथमिकता देने और दूसरों की राय की कम परवाह करने के लिए हुआ है। चाहे वह शिक्षा, कार्य, या व्यवसाय प्रबंधन में हो, आप प्रतिभा, दयालुता (उन लोगों के लिए जिन्हें आप अच्छा मानते हैं) और सुंदर व्यक्तियों के प्रति आकर्षण प्रदर्शित करके उत्कृष्टता प्राप्त करते हैं। जीवन के विभिन्न पहलुओं में भाग्य आपका साथ देता प्रतीत होता है।`,
        `यदि आप छठे नंबर के व्यक्ति हैं, तो आप कई लड़कियों का ध्यान आकर्षित कर सकते हैं और घर बसाने से पहले कई रिश्तों में शामिल हो सकते हैं। अगर आप लड़की हैं तो जल्दी शादी या सगाई होना आम बात है। परिवार और दोस्तों के लिए आपकी चिंता स्पष्ट है।`,
        `आधे पड़ाव के करीब पहुंचकर आपको शारीरिक और मानसिक चुनौतियों का सामना करना पड़ सकता है। आम तौर पर, आप आंतरिक-घर की खुशी को बढ़ावा देते हैं और करुणा, आराम, निष्पक्षता, घरेलू जिम्मेदारी और अच्छे निर्णय के गुण रखते हैं। आपके देखभाल करने वाले स्वभाव में एक अधिक प्रेमपूर्ण दुनिया में योगदान देने की शक्ति है।`,
      ],
      subContent: [
        `भाग्य आप पर मुस्कुराता है, कार, घर, महंगे मोबाइल, घड़ियाँ और कपड़े जैसी शानदार संपत्ति प्रदान करता है। उम्र की परवाह किए बिना, आप आनंद की तलाश में जीवन के प्रति युवा दृष्टिकोण बनाए रखते हैं।`,
        `एक चुंबकीय और आकर्षक व्यक्तित्व आपको अपने समूह या मित्र मंडली में प्रसिद्ध बनाता है, विपरीत लिंग का ध्यान आकर्षित करता है।`,
        `रचनात्मकता एक मजबूत पक्ष है, और आप एक मनोरंजनकर्ता के रूप में उत्कृष्टता प्राप्त करते हैं।`,
        `जिम्मेदारी आपके स्वभाव का हिस्सा है, जो आपको एक प्रबंधक के रूप में विश्वसनीय और प्रभावी बनाती है।`,
        `आपकी शारीरिक बनावट की चेतना स्पष्ट है।`,
        `आप अशांत वातावरण और बहस से बचते हैं, फिर भी बहस में एक प्रबल प्रतिद्वंद्वी हो सकते हैं।`,
        `प्रेम की कला में विशेषज्ञता के साथ रोमांटिक, आपके कई रिश्ते हो सकते हैं।`,
        `विलासिता की वस्तुओं या ज़रूरतों पर खुलकर ख़र्च करना आम बात है।`,
        `सुंदरता की सराहना जीवन के विभिन्न पहलुओं तक फैली हुई है।`,
        `भावनात्मक गहराई एक विशेषता है, लेकिन आप प्यार में आसानी से ऊब सकते हैं।`,
        `अभिनव सोच और परिवर्तन के लिए प्राथमिकता उल्लेखनीय लक्षण हैं।`,
        `आलस्य और ऊर्जा की कमी के दौर का अनुभव हो सकता है।`,
      ],
    },
    {
      conductorNumber: 6,
      mainTitle: "તમારી ભાગ્યાંક ૬ છે",
      subTitle: "તમારી પાસે શુક્રના લક્ષણો છે",
      language: "gu",
      mainContent: [
        `તમે જીવનનો સ્વાદ માણવા માટે જન્મ્યા છો, આનંદને પ્રાધાન્ય આપો અને અન્યના મંતવ્યો વિશે ઓછું ધ્યાન રાખો. પછી ભલે તે શિક્ષણ, કાર્ય અથવા વ્યવસાય સંચાલનમાં હોય, તમે પ્રતિભા દર્શાવતા, દયા (જેને તમે સરસ માનો છો) અને સુંદર વ્યક્તિઓ પ્રત્યે આકર્ષણ દર્શાવો છો. જીવનના વિવિધ પાસાઓમાં ભાગ્ય તમારી તરફેણ કરતું હોય તેવું લાગે છે.`,
        `જો તમે છઠ્ઠા નંબરના માણસ છો, તો તમે સ્થાયી થતાં પહેલાં ઘણી છોકરીઓનું ધ્યાન અનુભવી શકો છો અને બહુવિધ સંબંધોમાં જોડાઈ શકો છો. જો તમે છોકરી છો, તો વહેલા લગ્ન અથવા સગાઈ સામાન્ય છે. કુટુંબ અને મિત્રો માટે તમારી ચિંતા સ્પષ્ટ છે.`,
        `હાફવે માર્કની નજીક, તમારે શારીરિક અને માનસિક પડકારોનો સામનો કરવો પડી શકે છે. સામાન્ય રીતે, તમે આંતરિક-ઘરની ખુશીને પ્રોત્સાહન આપો છો અને કરુણા, આરામ, ન્યાયીપણું, ઘરેલું જવાબદારી અને સારા નિર્ણયના ગુણો ધરાવો છો. તમારી સંભાળ રાખનાર સ્વભાવમાં વધુ પ્રેમાળ વિશ્વમાં યોગદાન આપવાની શક્તિ છે.`,
      ],
      subContent: [
        `કાર, ઘર, મોંઘા મોબાઈલ, ઘડિયાળો અને કપડાં જેવી વૈભવી સંપત્તિ પ્રદાન કરીને નસીબ તમારા પર સ્મિત કરે છે. ઉંમરને ધ્યાનમાં લીધા વિના, તમે આનંદની શોધમાં, જીવન પ્રત્યે યુવા દૃષ્ટિકોણ જાળવી રાખો છો.`,
        `ચુંબકીય અને આકર્ષક વ્યક્તિત્વ તમને તમારા જૂથ અથવા મિત્ર વર્તુળમાં જાણીતા બનાવે છે, વિરોધી લિંગનું ધ્યાન આકર્ષિત કરે છે.`,
        `સર્જનાત્મકતા એ એક મજબૂત પોશાક છે, અને તમે મનોરંજન કરનાર તરીકે શ્રેષ્ઠ છો.`,
        `જવાબદારી એ તમારા સ્વભાવનો એક ભાગ છે, જે તમને મેનેજર તરીકે વિશ્વસનીય અને અસરકારક બનાવે છે.`,
        `તમારા શારીરિક દેખાવની સભાનતા સ્પષ્ટ છે.`,
        `તમે અવ્યવસ્થિત વાતાવરણ અને દલીલોને ટાળો છો, છતાં ચર્ચામાં પ્રચંડ પ્રતિસ્પર્ધી બની શકો છો.`,
        `પ્રેમની કળામાં નિપુણતા સાથે રોમેન્ટિક, તમારી પાસે ઘણા સંબંધો હોઈ શકે છે.`,
        `લક્ઝરી વસ્તુઓ અથવા જરૂરિયાતો પર મુક્તપણે ખર્ચ કરવો સામાન્ય બાબત છે.`,
        `સુંદરતાની પ્રશંસા જીવનના વિવિધ પાસાઓ સુધી વિસ્તરે છે.`,
        `ભાવનાત્મક ઊંડાણ એ એક લાક્ષણિકતા છે, પરંતુ તમે પ્રેમમાં સરળતાથી કંટાળી શકો છો.`,
        `નવીન વિચારસરણી અને પરિવર્તન માટેની પસંદગી એ નોંધપાત્ર લક્ષણો છે.`,
        `આળસ અને ઉર્જાનો અભાવ અનુભવી શકે છે.`,
      ],
    },
    {
      conductorNumber: 7,
      mainTitle: "Your Bhagyanka is 7",
      subTitle: "You have traits of a Ketu/The Shadow",
      language: "en",
      mainContent: [
        `You possess the ability to attract anyone with your realistic, confident, and happy demeanour. Your talents span education, music, arts, singing, and acting. However, bad tempers may pose a challenge. If you are a girl, you excel in the mentioned subjects and value your family status. For guys, popularity with girls is common, accompanied by talent. Many sevens face marital problems, and despite having everything, a sense of unfulfillment lingers.`,
        `The Lord may have bestowed unusual human abilities upon you, leading to potential family life challenges. Seeking a partner actively is advised to avoid being single. You are described as a wonderful, friendly, artistic, and happy person destined to contribute significantly to the world.`,
      ],
      subContent: [
        `You are philosophical by nature and have the potential to become an excellent scholar if your destiny and name numbers align.`,
        `Your brain is hyperactive, leading to restlessness due to an overly busy mind.`,
        `While you generally talk less, your words hold substance, making you an effective speaker.`,
        `Your mind is adaptable, changing often and influenced by others. You easily adjust to different environments.`,
        `Expressive and romantic in relationships, you possess sensual qualities.`,
        `Your magnetic personality attracts many people.`,
        `A secretive nature prevails; you do not readily open up.`,
        `Good intuitive powers contribute to the originality of your work.`,
        `High sensitivity characterizes you.`,
        `Decision-making may be challenging, with a tendency to regret quick decisions or take too much time due to confusion.`,
        `Spiritual, religious, and compassionate qualities are part of your nature.`,
        `Personal liberty is valued, and injustice is intolerable.`,
        `Early life involves significant struggles.`,
      ],
    },
    {
      conductorNumber: 7,
      mainTitle: "आपका भाग्यांक ७ है",
      subTitle: "आपमें केतु/छाया के लक्षण हैं",
      language: "hi",
      mainContent: [
        "आपमें अपने यथार्थवादी, आत्मविश्वासी और प्रसन्न व्यवहार से किसी को भी आकर्षित करने की क्षमता है। आपकी प्रतिभाओं में शिक्षा, संगीत, कला, गायन और अभिनय शामिल हैं। हालाँकि, ख़राब स्वभाव चुनौती खड़ी कर सकता है। यदि आप एक लड़की हैं, तो आप उल्लिखित विषयों में उत्कृष्टता प्राप्त करती हैं और अपनी पारिवारिक स्थिति को महत्व देती हैं। लड़कों के लिए, प्रतिभा के साथ-साथ लड़कियों के बीच लोकप्रियता आम बात है। कई सातों को वैवाहिक समस्याओं का सामना करना पड़ता है, और सब कुछ होने के बावजूद, अतृप्ति की भावना बनी रहती है।",
        `भगवान ने आपको असामान्य मानवीय क्षमताएं प्रदान की होंगी, जिससे पारिवारिक जीवन में संभावित चुनौतियाँ पैदा होंगी। अकेले रहने से बचने के लिए सक्रिय रूप से साथी की तलाश करने की सलाह दी जाती है। आपको एक अद्भुत, मिलनसार, कलात्मक और खुशमिजाज़ व्यक्ति के रूप में वर्णित किया गया है जो दुनिया में महत्वपूर्ण योगदान देने के लिए तैयार है।`,
      ],
      subContent: [
        `आप स्वभाव से दार्शनिक हैं और यदि आपका भाग्य और नाम अंक संरेखित हों तो आप एक उत्कृष्ट विद्वान बनने की क्षमता रखते हैं।`,
        `आपका मस्तिष्क अतिसक्रिय है, अत्यधिक व्यस्त दिमाग के कारण बेचैनी होती है।`,
        `हालांकि आप आम तौर पर कम बोलते हैं, आपके शब्दों में दम होता है, जो आपको एक प्रभावी वक्ता बनाता है।`,
        `आपका दिमाग अनुकूलनीय है, अक्सर बदलता रहता है और दूसरों से प्रभावित होता है। आप आसानी से विभिन्न वातावरणों में समायोजित हो जाते हैं।`,
        `रिश्तों में अभिव्यंजक और रोमांटिक, आपमें कामुक गुण हैं।`,
        `आपका चुंबकीय व्यक्तित्व कई लोगों को आकर्षित करता है।`,
        `एक गुप्त प्रकृति प्रबल होती है; आप आसानी से नहीं खुलते।`,
        `अच्छी सहज ज्ञान युक्त शक्तियां आपके काम की मौलिकता में योगदान करती हैं।`,
        `उच्च संवेदनशीलता आपकी विशेषता है।`,
        `निर्णय लेना चुनौतीपूर्ण हो सकता है, त्वरित निर्णयों पर पछतावा होने या भ्रम के कारण बहुत अधिक समय लगने की प्रवृत्ति हो सकती है।`,
        `आध्यात्मिक, धार्मिक और दयालु गुण आपके स्वभाव का हिस्सा हैं।`,
        `व्यक्तिगत स्वतंत्रता को महत्व दिया जाता है, और अन्याय असहनीय है।`,
        `प्रारंभिक जीवन में महत्वपूर्ण संघर्ष शामिल हैं।`,
      ],
    },
    {
      conductorNumber: 7,
      mainTitle: "તમારી ભાગ્યાંક ૭ છે",
      subTitle: "તમારી પાસે કેતુ/છાયાના લક્ષણો છે",
      language: "gu",
      mainContent: [
        `તમારી પાસે તમારા વાસ્તવિક, આત્મવિશ્વાસપૂર્ણ અને આનંદી વર્તનથી કોઈપણને આકર્ષિત કરવાની ક્ષમતા છે. તમારી પ્રતિભા શિક્ષણ, સંગીત, કળા, ગાયન અને અભિનયમાં ફેલાયેલી છે. જો કે, ખરાબ સ્વભાવ એક પડકાર બની શકે છે. જો તમે છોકરી છો, તો તમે ઉલ્લેખિત વિષયોમાં શ્રેષ્ઠ છો અને તમારા કુટુંબની સ્થિતિને મહત્ત્વ આપો છો. છોકરાઓ માટે, છોકરીઓ સાથે લોકપ્રિયતા સામાન્ય છે, પ્રતિભા સાથે. ઘણા સાત લોકો વૈવાહિક સમસ્યાઓનો સામનો કરે છે, અને બધું હોવા છતાં, અપૂર્ણતાની લાગણી ટકી રહે છે.`,
        `ભગવાનએ તમને અસામાન્ય માનવ ક્ષમતાઓ આપી હશે, જે સંભવિત કૌટુંબિક જીવન પડકારો તરફ દોરી જશે. સક્રિય રીતે જીવનસાથીની શોધમાં સિંગલ રહેવાનું ટાળવાની સલાહ આપવામાં આવે છે. તમને એક અદ્ભુત, મૈત્રીપૂર્ણ, કલાત્મક અને સુખી વ્યક્તિ તરીકે વર્ણવવામાં આવે છે જે વિશ્વમાં નોંધપાત્ર યોગદાન આપવાનું નક્કી કરે છે.`,
      ],
      subContent: [
        `તમે સ્વભાવે દાર્શનિક છો અને જો તમારું ભાગ્ય અને નામની સંખ્યા સંરેખિત હોય તો તમે ઉત્તમ વિદ્વાન બનવાની ક્ષમતા ધરાવો છો.`,
        `તમારું મગજ હાયપરએક્ટિવ છે, જે વધુ પડતા વ્યસ્ત મનને કારણે બેચેની તરફ દોરી જાય છે.`,
        `જ્યારે તમે સામાન્ય રીતે ઓછું બોલો છો, ત્યારે તમારા શબ્દોમાં તત્વ હોય છે, જે તમને અસરકારક વક્તા બનાવે છે.`,
        `તમારું મન અનુકૂલનક્ષમ છે, વારંવાર બદલાતું રહે છે અને અન્ય લોકોથી પ્રભાવિત થાય છે. તમે સરળતાથી અલગ-અલગ વાતાવરણમાં એડજસ્ટ થઈ શકો છો.`,
        `સંબંધોમાં અભિવ્યક્ત અને રોમેન્ટિક, તમે વિષયાસક્ત ગુણો ધરાવો છો.`,
        `તમારું ચુંબકીય વ્યક્તિત્વ ઘણા લોકોને આકર્ષે છે.`,
        `એક ગુપ્ત પ્રકૃતિ પ્રવર્તે છે; તમે સહેલાઈથી ખોલતા નથી.`,
        `સારી સાહજિક શક્તિઓ તમારા કાર્યની મૌલિકતામાં ફાળો આપે છે.`,
        `ઉચ્ચ સંવેદનશીલતા તમને લાક્ષણિકતા આપે છે.`,
        `ઝડપી નિર્ણયો પર પસ્તાવો કરવાની અથવા મૂંઝવણને કારણે ઘણો સમય લાગવાની વૃત્તિ સાથે નિર્ણય લેવાની પ્રક્રિયા પડકારરૂપ હોઈ શકે છે.`,
        `આધ્યાત્મિક, ધાર્મિક અને દયાળુ ગુણો તમારા સ્વભાવનો ભાગ છે.`,
        `વ્યક્તિગત સ્વતંત્રતા મૂલ્યવાન છે, અને અન્યાય અસહ્ય છે.`,
        `પ્રારંભિક જીવનમાં નોંધપાત્ર સંઘર્ષનો સમાવેશ થાય છે.`,
      ],
    },
    {
      conductorNumber: 8,
      mainTitle: "Your Bhagyanka is 8",
      subTitle: "You have traits of a Saturn/The Judge",
      language: "en",
      mainContent: [
        `You possess a very strong personality, often misunderstood by others. Your ability to pinpoint and declare, "This is what," is a defining trait. Early years may involve suffering. Life experiences teach you practical lessons, and you are likely to be a solitary individual, reserved with a small circle of friends but always ready to help others.`,
        `Marriage, usually occurring later in life, brings some relief from bad luck. However, unforeseen challenges, such as errors, government issues, poisonous animals, and accidents, may arise. Your character is marked by discipline, persistence, courage, and strength, making you a valuable member of a family team. You are a fighter.`,
      ],
      subContent: [
        `Strong willpower: You never lose hope in life, facing failures and obstacles with resilience.`,
        `Fighter mentality: You refuse to accept defeat easily and persist in your efforts until you feel correct.`,
        `Hardworking nature: You excel at laborious work, with energy derived from Saturn, yielding results later in life.`,
        `Patience: You make decisions thoughtfully and lead a planned life.`,
        `Modesty: Despite success, you remain modest, simple, and down-to-earth.`,
        `Readiness for challenges: You accept challenges willingly and fearlessly.`,
        `Self-centered: You keep your inner feelings private, only sharing with those very close to you.`,
        `Struggle: Obstacles and delays are common, requiring resilience.`,
        `Love relationships: You may face challenges and failures in love, requiring caution.`,
        `Vengefulness: Deception may lead to difficulty in forgiveness.`,
        `Substance abuse: There is a risk of addiction to drugs and alcohol.`,
        `Independence: You prefer doing things yourself and dislike seeking assistance.`,
        `Loneliness: Misunderstood by friends and relatives, you may feel lonely at heart.`,
        `Aspiration for great success: Small successes are not satisfying; you aim for significant achievements and honor.`,
        `Dislike for hypocrisy and deceit: You have a strong aversion to insincerity and dishonesty.`,
      ],
    },
    {
      conductorNumber: 8,
      mainTitle: "आपका भाग्यांक ८ है",
      subTitle: "आपमें शनि/न्यायाधीश के गुण हैं",
      language: "hi",
      mainContent: [
        `आपका व्यक्तित्व बहुत मजबूत है, अक्सर दूसरे लोग इसे गलत समझ लेते हैं। आपकी पहचान करने और घोषित करने की क्षमता, "यही है," एक परिभाषित विशेषता है। प्रारंभिक वर्षों में कष्ट हो सकता है। जीवन के अनुभव आपको व्यावहारिक सबक सिखाते हैं, और आप एक अकेले व्यक्ति होने की संभावना रखते हैं, दोस्तों के एक छोटे समूह के साथ आरक्षित होते हैं लेकिन दूसरों की मदद के लिए हमेशा तैयार रहते हैं।`,
        `शादी, जो आमतौर पर जीवन में देर से होती है, दुर्भाग्य से कुछ राहत दिलाती है। हालाँकि, त्रुटियाँ, सरकारी मुद्दे, ज़हरीले जानवर और दुर्घटनाएँ जैसी अप्रत्याशित चुनौतियाँ उत्पन्न हो सकती हैं। आपका चरित्र अनुशासन, दृढ़ता, साहस और ताकत से चिह्नित है, जो आपको पारिवारिक टीम का एक मूल्यवान सदस्य बनाता है। आप एक योद्धा हैं।`,
      ],
      subContent: [
        `दृढ़ इच्छाशक्ति: आप जीवन में कभी भी आशा नहीं खोते, असफलताओं और बाधाओं का लचीलेपन के साथ सामना करते हैं।`,
        "लड़ाकू मानसिकता: आप हार को आसानी से स्वीकार करने से इनकार करते हैं और अपने प्रयासों में तब तक लगे रहते हैं जब तक आपको सही महसूस न हो जाए।",
        `मेहनती प्रकृति: आप शनि से प्राप्त ऊर्जा के साथ परिश्रमी कार्यों में उत्कृष्टता प्राप्त करते हैं, जिसका परिणाम जीवन में बाद में मिलता है।`,
        "धैर्य: आप सोच-समझकर निर्णय लेते हैं और योजनाबद्ध जीवन जीते हैं।",
        `विनम्रता: सफलता के बावजूद, आप विनम्र, सरल और व्यावहारिक बने रहते हैं।`,
        `चुनौतियों के लिए तत्परता: आप चुनौतियों को स्वेच्छा से और निडर होकर स्वीकार करते हैं।`,
        `आत्मकेंद्रित: आप अपनी आंतरिक भावनाओं को निजी रखते हैं, केवल उन लोगों के साथ साझा करते हैं जो आपके बहुत करीब हैं।`,
        `संघर्ष: बाधाएं और देरी आम बात है, इसके लिए लचीलेपन की आवश्यकता होती है।`,
        `प्रेम संबंध: आपको प्यार में चुनौतियों और असफलताओं का सामना करना पड़ सकता है, सावधानी की आवश्यकता है।`,
        "प्रतिशोध: धोखे से क्षमा करने में कठिनाई हो सकती है।",
        `मादक द्रव्यों का सेवन: नशीली दवाओं और शराब की लत का खतरा है।`,
        `स्वतंत्रता: आप काम स्वयं करना पसंद करते हैं और सहायता मांगना नापसंद करते हैं।`,
        `अकेलापन: दोस्तों और रिश्तेदारों द्वारा ग़लत समझे जाने पर, आप दिल से अकेलापन महसूस कर सकते हैं।`,
        `बड़ी सफलता की आकांक्षा: छोटी सफलताएँ संतोषजनक नहीं होतीं; आपका लक्ष्य महत्वपूर्ण उपलब्धियाँ और सम्मान है।`,
        "पाखंड और छल से नापसंद: आपको कपट और बेईमानी से सख्त नफरत है।",
      ],
    },
    {
      conductorNumber: 8,
      mainTitle: "તમારી ભાગ્યાંક ૮ છે",
      subTitle: "તમારામાં શનિ/ન્યાયાધીશના લક્ષણો છે",
      language: "gu",
      mainContent: [
        `તમે ખૂબ જ મજબૂત વ્યક્તિત્વ ધરાવો છો, ઘણીવાર અન્ય લોકો દ્વારા ગેરસમજ થાય છે. નિર્ધારિત કરવાની અને "આ તે શું છે" તે જાહેર કરવાની તમારી ક્ષમતા એ એક નિર્ણાયક લક્ષણ છે. શરૂઆતના વર્ષોમાં દુઃખનો સમાવેશ થઈ શકે છે. જીવનના અનુભવો તમને વ્યવહારુ પાઠ શીખવે છે, અને તમે એકાંત વ્યક્તિ છો, મિત્રોના નાના વર્તુળ સાથે આરક્ષિત છો પરંતુ હંમેશા અન્યને મદદ કરવા તૈયાર છો.`,
        `લગ્ન, સામાન્ય રીતે જીવનમાં પાછળથી થાય છે, તે ખરાબ નસીબમાંથી થોડી રાહત લાવે છે. જો કે, અણધાર્યા પડકારો, જેમ કે ભૂલો, સરકારી સમસ્યાઓ, ઝેરી પ્રાણીઓ અને અકસ્માતો, ઊભી થઈ શકે છે. તમારું પાત્ર શિસ્ત, દ્રઢતા, હિંમત અને શક્તિ દ્વારા ચિહ્નિત થયેલ છે, જે તમને કુટુંબની ટીમના મૂલ્યવાન સભ્ય બનાવે છે. તમે ફાઇટર છો.`,
      ],
      subContent: [
        `મજબૂત ઈચ્છાશક્તિ: તમે નિષ્ફળતાઓ અને અવરોધોનો પ્રતિકાર સાથે સામનો કરીને જીવનમાં ક્યારેય આશા ગુમાવશો નહીં.`,
        `લડાયક માનસિકતા: તમે સરળતાથી હાર સ્વીકારવાનો ઇનકાર કરો છો અને જ્યાં સુધી તમને સાચું ન લાગે ત્યાં સુધી તમારા પ્રયત્નો ચાલુ રાખો.`,
        `મહેનતુ સ્વભાવ: તમે શનિમાંથી મેળવેલી ઉર્જા સાથે મહેનતભર્યા કામમાં ઉત્કૃષ્ટ બનો છો, જે જીવનમાં પાછળથી પરિણામ આપે છે.`,
        `ધીરજ: તમે સમજી વિચારીને નિર્ણયો લો અને આયોજનબદ્ધ જીવન જીવો.`,
        `નમ્રતા: સફળતા હોવા છતાં, તમે વિનમ્ર, સરળ અને ડાઉન ટુ અર્થ રહો છો.`,
        `પડકારો માટે તત્પરતા: તમે સ્વેચ્છાએ અને નિર્ભયતાથી પડકારોને સ્વીકારો છો.`,
        `સ્વ-કેન્દ્રિત: તમે તમારી આંતરિક લાગણીઓને ખાનગી રાખો છો, ફક્ત તમારી નજીકના લોકો સાથે જ શેર કરો છો.`,
        `સંઘર્ષ: અવરોધો અને વિલંબ સામાન્ય છે, જેમાં સ્થિતિસ્થાપકતાની જરૂર હોય છે.`,
        `પ્રેમ સંબંધો: તમારે પ્રેમમાં પડકારો અને નિષ્ફળતાઓનો સામનો કરવો પડી શકે છે, સાવચેતી રાખવાની જરૂર છે.`,
        `વેરભાવ: છેતરપિંડીથી ક્ષમા કરવામાં મુશ્કેલી આવી શકે છે.`,
        `પદાર્થોનો દુરુપયોગ: ડ્રગ્સ અને આલ્કોહોલનું વ્યસન થવાનું જોખમ છે.`,
        `સ્વતંત્રતા: તમે વસ્તુઓ જાતે કરવાનું પસંદ કરો છો અને મદદ લેવી નાપસંદ કરો છો.`,
        `એકલતા: મિત્રો અને સંબંધીઓ દ્વારા ગેરસમજ, તમે હૃદયમાં એકલતા અનુભવી શકો છો.`,
        `મહાન સફળતાની આકાંક્ષાઃ નાની સફળતાઓ સંતોષકારક નથી હોતી; તમે નોંધપાત્ર સિદ્ધિઓ અને સન્માનનું લક્ષ્ય રાખો છો.`,
        `દંભ અને છેતરપિંડી માટે અણગમો: તમને નિષ્ઠાવાનતા અને અપ્રમાણિકતા પ્રત્યે સખત અણગમો છે.`,
      ],
    },
    {
      conductorNumber: 9,
      mainTitle: "Your Bhagyanka is 9",
      subTitle: "You have traits of a Mars/The Commander",
      language: "en",
      mainContent: [
        `If you were born on the 9th, 18th, or 27th of any month as a Psychic Number 9, your basic characteristics include`,
        `Your life path, according to this interpretation, involves facing challenges and overcoming difficulties. You serve as an inspiration to others, embodying qualities of hard work, courage, and determination.`,
      ],
      subContent: [
        `High energy: You possess a significant amount of energy, and your challenge lies in learning how to use it effectively.`,
        `Hardworking: You are a determined and hardworking individual, demonstrating full commitment to your tasks. This quality is one of your strongest positives.`,
        `Courageous: Your courage is notable, and you are not afraid to face challenges, even engaging with enemies without a weapon. Additionally, you can serve as a motivating force for those around you.`,
        `Energetic and optimistic: Despite occasional emotional moments, you generally exude energy and optimism. While you may appear strong and stubborn externally, there is a softer and emotional side within you.`,
        `Preferential to requests over orders: You don't respond well to orders but prefer tasks framed as requests. Your actions are driven by love rather than force.`,
        `Restless:You have a restless nature, choosing to work for extended periods rather than sitting quietly.`,
        `Arrogance:There may be moments of arrogance when you try to impose your perspective on others. Persistence is one of your traits, and you don't give up easily.`,
        `Irritability: At times, you might become irritable and engage in conflicts with those around you.`,
        `Overconfidence: There is a tendency to become overconfident occasionally.`,
        `Dislike interference and criticism: You do not appreciate interference in your work and strongly dislike criticism.`,
      ],
    },
    {
      conductorNumber: 9,
      mainTitle: "आपका भाग्यांक ९ है",
      subTitle: "आपमें मंगल/कमांडर के लक्षण हैं",
      language: "hi",
      mainContent: [
        `यदि आपका जन्म किसी भी महीने की 9, 18, या 27 तारीख को मानसिक अंक 9 के रूप में हुआ है, तो आपकी बुनियादी विशेषताओं में शामिल हैं`,
        `इस व्याख्या के अनुसार, आपके जीवन पथ में चुनौतियों का सामना करना और कठिनाइयों पर काबू पाना शामिल है। आप कड़ी मेहनत, साहस और दृढ़ संकल्प के गुणों को अपनाकर दूसरों के लिए प्रेरणा बनते हैं।`,
      ],
      subContent: [
        `उच्च ऊर्जा: आपके पास पर्याप्त मात्रा में ऊर्जा है, और आपकी चुनौती यह सीखने में है कि इसका प्रभावी ढंग से उपयोग कैसे किया जाए।`,
        `मेहनती: आप एक दृढ़निश्चयी और मेहनती व्यक्ति हैं, जो अपने कार्यों के प्रति पूर्ण प्रतिबद्धता प्रदर्शित करते हैं। यह गुण आपकी सबसे मजबूत सकारात्मकताओं में से एक है।`,
        `साहसी: आपका साहस उल्लेखनीय है, और आप चुनौतियों का सामना करने से नहीं डरते, यहाँ तक कि बिना हथियार के दुश्मनों से उलझने से भी नहीं डरते। इसके अतिरिक्त, आप अपने आस-पास के लोगों के लिए एक प्रेरक शक्ति के रूप में काम कर सकते हैं।`,
        `ऊर्जावान और आशावादी: कभी-कभार भावनात्मक क्षणों के बावजूद, आप आम तौर पर ऊर्जा और आशावाद दिखाते हैं। हालांकि आप बाहर से मजबूत और जिद्दी दिख सकते हैं, लेकिन आपके भीतर एक नरम और भावनात्मक पक्ष भी है।`,
        `आदेशों के मुकाबले अनुरोधों को तरजीह: आप आदेशों पर अच्छी प्रतिक्रिया नहीं देते हैं लेकिन अनुरोधों के रूप में तैयार किए गए कार्यों को प्राथमिकता देते हैं। आपके कार्य बल के बजाय प्रेम से प्रेरित होते हैं।`,
        `बेचैन: आपका स्वभाव बेचैन करने वाला है, आप चुपचाप बैठने के बजाय लंबे समय तक काम करना पसंद करते हैं।`,
        `अहंकार: जब आप अपना दृष्टिकोण दूसरों पर थोपने का प्रयास करते हैं तो अहंकार के क्षण आ सकते हैं। दृढ़ता आपके गुणों में से एक है, और आप आसानी से हार नहीं मानते।`,
        `चिड़चिड़ापन: कभी-कभी, आप चिड़चिड़े हो सकते हैं और अपने आस-पास के लोगों के साथ झगड़ सकते हैं।`,
        `अति आत्मविश्वास: कभी-कभी अति आत्मविश्वासी बनने की प्रवृत्ति होती है।`,
        `हस्तक्षेप और आलोचना नापसंद: आप अपने काम में हस्तक्षेप की सराहना नहीं करते हैं और आलोचना को सख्त नापसंद करते हैं।`,
      ],
    },
    {
      conductorNumber: 9,
      mainTitle: "તમારી ભાગ્યાંક ૯ છે",
      subTitle: "તમારામાં મંગળ/કમાન્ડરના લક્ષણો છે",
      language: "gu",
      mainContent: [
        `જો તમારો જન્મ કોઈપણ મહિનાની 9મી, 18મી અથવા 27મી તારીખે માનસિક નંબર 9 તરીકે થયો હોય, તો તમારી મૂળભૂત લાક્ષણિકતાઓમાં સમાવેશ થાય છે`,
        `આ અર્થઘટન મુજબ તમારા જીવન માર્ગમાં પડકારોનો સામનો કરવો અને મુશ્કેલીઓનો સામનો કરવાનો સમાવેશ થાય છે. તમે સખત મહેનત, હિંમત અને નિશ્ચયના ગુણોને મૂર્તિમંત કરીને અન્ય લોકો માટે પ્રેરણારૂપ છો.`,
      ],
      subContent: [
        `ઉચ્ચ ઉર્જા: તમારી પાસે ઉર્જાનો નોંધપાત્ર જથ્થો છે, અને તમારો પડકાર તેનો અસરકારક રીતે ઉપયોગ કેવી રીતે કરવો તે શીખવાનો છે.`,
        `મહેનત: તમે એક નિશ્ચિત અને મહેનતુ વ્યક્તિ છો, તમારા કાર્યો પ્રત્યે સંપૂર્ણ પ્રતિબદ્ધતા દર્શાવો છો. આ ગુણવત્તા તમારા સૌથી મજબૂત સકારાત્મક ગુણોમાંની એક છે.`,
        `હિંમતવાન: તમારી હિંમત નોંધનીય છે, અને તમે શસ્ત્ર વિના દુશ્મનો સાથે પણ જોડાઈને પડકારોનો સામનો કરવામાં ડરતા નથી. વધુમાં, તમે તમારી આસપાસના લોકો માટે પ્રેરક બળ તરીકે સેવા આપી શકો છો.`,
        `ઊર્જાવાન અને આશાવાદી: પ્રસંગોપાત ભાવનાત્મક ક્ષણો હોવા છતાં, તમે સામાન્ય રીતે ઉર્જા અને આશાવાદ ફેલાવો છો. જ્યારે તમે બાહ્ય રીતે મજબૂત અને હઠીલા દેખાશો, તમારી અંદર એક નરમ અને ભાવનાત્મક બાજુ છે.`,
        `ઓર્ડર્સ કરતાં વિનંતીઓને પ્રેફરન્શિયલ: તમે ઓર્ડરનો સારો પ્રતિસાદ આપતા નથી પરંતુ વિનંતીઓ તરીકે ફ્રેમ કરેલા કાર્યોને પસંદ કરો છો. તમારી ક્રિયાઓ બળને બદલે પ્રેમથી ચાલે છે.`,
        `બેચેન: તમે બેચેન સ્વભાવ ધરાવો છો, શાંતિથી બેસી રહેવાને બદલે લાંબા સમય સુધી કામ કરવાનું પસંદ કરો છો.`,
        `ઘમંડ: જ્યારે તમે તમારા દ્રષ્ટિકોણને અન્ય લોકો પર લાદવાનો પ્રયાસ કરો છો ત્યારે ઘમંડની ક્ષણો આવી શકે છે. દ્રઢતા એ તમારા લક્ષણોમાંનું એક છે અને તમે સરળતાથી હાર માનતા નથી.`,
        `ચીડિયાપણું: અમુક સમયે, તમે ચિડાઈ જાઓ છો અને તમારી આસપાસના લોકો સાથે તકરારમાં વ્યસ્ત થઈ શકો છો.`,
        `અતિ આત્મવિશ્વાસ: ક્યારેક-ક્યારેક વધુ પડતા આત્મવિશ્વાસની વૃત્તિ હોય છે.`,
        `દખલગીરી અને ટીકાને નાપસંદ કરો: તમે તમારા કામમાં દખલગીરીની કદર કરતા નથી અને ટીકાને સખત નાપસંદ કરો છો.`,
      ],
    },
  ]);
}
